
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int conjuntoExp = 22;
  public static final int TKConj = 13;
  public static final int TKAsterisco = 8;
  public static final int conjunto = 21;
  public static final int cadena = 15;
  public static final int TKMas = 7;
  public static final int caracterespecial = 16;
  public static final int TKGuion = 19;
  public static final int TKParC = 3;
  public static final int TKPunto = 6;
  public static final int TKParA = 2;
  public static final int TKDosPuntos = 14;
  public static final int TKPuntoComa = 10;
  public static final int EOF = 0;
  public static final int id = 23;
  public static final int TKColocho = 12;
  public static final int TKBarra = 5;
  public static final int TKInterrogacion = 11;
  public static final int error = 1;
  public static final int entero = 17;
  public static final int TKComa = 4;
  public static final int TKMayor = 20;
  public static final int TKPorcentaje = 9;
  public static final int identificador = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TKParA",
  "TKParC",
  "TKComa",
  "TKBarra",
  "TKPunto",
  "TKMas",
  "TKAsterisco",
  "TKPorcentaje",
  "TKPuntoComa",
  "TKInterrogacion",
  "TKColocho",
  "TKConj",
  "TKDosPuntos",
  "cadena",
  "caracterespecial",
  "entero",
  "identificador",
  "TKGuion",
  "TKMayor",
  "conjunto",
  "conjuntoExp",
  "id"
  };
}

